### ISSUE TITLE
[feature request] TypeScriptの型定義ファイルがほしい

### ISSUE THREAD

**Issue by rinsuki** [akameco/styled-style#1]
**Do you want to request a *feature* or report a *bug*?:** feature

**What is the current behavior?:** TypeScript用の型定義がない(ため、`tsconfig.json`で`noImplictitAny`を`true`にしているとimport文でimportできなかったりいろいろ不便)。
![app_tsx_ _slackdeck](https://user-images.githubusercontent.com/6533808/35816509-3d92d8de-0ade-11e8-974f-63202f877a51.png)

**What is the expected behavior?:** TypeScript用の型定義ファイルが存在し、`tsconfig.json`で`noImplictitAny`を`true`にしている環境でもimport文でimportできるようになる

**Suggested solution:** 🤔 

ref: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by akameco** [comment]
@rinsuki レポートありがとうございます🙏
あまり`TypeScript`の経験がなくて型定義ファイルの作成方法がわかりません。
もちろんあったほうがいいことは確かなので調べてみます。

**Comment by akameco** [comment]
#2 により解決しました🎉
